// <auto-generated />
namespace SAMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createbasedatatable201701143 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createbasedatatable201701143));
        
        string IMigrationMetadata.Id
        {
            get { return "201701140636494_create basedata table2017-01-14-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
