// <auto-generated />
namespace SAMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _10170123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10170123));
        
        string IMigrationMetadata.Id
        {
            get { return "201701230726080_10170123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
